name: autofix.ci

permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}

jobs:
  autofix:
    name: Format code
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@[[HASH_ACTIONS_CHECKOUT]]
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@[[HASH_PNPM_ACTIONSETUP]]

      - name: Install Node.js
        uses: actions/setup-node@[[HASH_ACTIONS_SETUPNODE]]
        with:
          cache: pnpm
          node-version: [[NODE_VERSION]]

      - name: Install dependencies
        run: pnpm install

      - name: Format code
        run: pnpm format

      - name: Run autofix
        uses: autofix-ci/action@[[HASH_AUTOFIXCI_ACTION]]
        with:
          fail-fast: false
