name: release

permissions: {}

on:
  push:
    branches:
      - main

jobs:
  changeset:
    name: Changeset
    if: ${{ github.repository_owner == '[[USER_NAME_LC]]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@[[HASH_ACTIONS_CHECKOUT]]
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@[[HASH_PNPM_ACTIONSETUP]]

      - name: Install Node.js
        uses: actions/setup-node@[[HASH_ACTIONS_SETUPNODE]]
        with:
          node-version: 24
          package-manager-cache: false

      - name: Install dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish
        uses: changesets/action@[[HASH_CHANGESETS_ACTION]]
        with:
          version: pnpm run version
          publish: pnpm changeset publish
          commit: 'ci: release'
          title: 'ci: release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: '' # https://github.com/changesets/changesets/issues/1152#issuecomment-3190884868
