name: release

permissions: {}

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  integration:
    name: Integration
    uses: ./.github/workflows/integration.yml

  publish:
    name: Publish
    needs:
      - integration
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@[[HASH_ACTIONS_CHECKOUT]]
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@[[HASH_PNPM_ACTIONSETUP]]

      - name: Install Node.js
        uses: actions/setup-node@[[HASH_ACTIONS_SETUPNODE]]
        with:
          cache: pnpm
          node-version: [[NODE_VERSION]]

      - name: Install dependencies
        run: pnpm install

      - name: Generate changelog
        run: pnpx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
